[[redirects]]
  from = "#/portfolio"
  to = "/work"
  [[redirects]]
  from = "#/blog"
  to = "/blog"
  [[redirects]]
  from = "#/blog/2"
  to = "/blog"
  [[redirects]]
  from = "#/contact"
  to = "/contact"
  [[redirects]]
  from = "#/"
  to = "/"
  [[redirects]]
  from = "#/about"
  to = "/about"